### PR TITLE
Update plugin folder name to `lighthouse-plugin-publisher-ads`.

### PR DESCRIPTION
**Pull request by jburger424**

### CODE REVIEW

**Comment by warrengm** [comment]
Is this blocking plugin integration or a issue about convention? Some more background on the PR description would be great

**Comment by jburger424** [comment]
> Is this blocking plugin integration or a issue about convention? Some more background on the PR description would be great

This is not blocking. Just a quick fix I wanted to get in to complete the name change.

**Comment by paulirish** [comment]
Time for some bikeshedding? 🚲🏚   😃 

I kinda miss "adspeed" as it communicated a lot.

* "audits" I think is superfluous as this is a lighthouse plugin and "audits" is kind of implied.
* "pub" or "publisher" makes sense from a google POV, but is it a common term from the publisher POV? 

The naming usecases i'm thinking of are... 1) someone is googling the name of this plugin that they heard about.. 2) they are selecting its checkbox in DevTools.

What about just "Google Ads" .. `lighthouse-plugin-google-ads` ?
Or if you don't want Google in there, then... 'Ad publishing' ?

**Comment by robhazan** [comment]
@paulirish pub/publisher is indeed a common industry term, and something that web content producers who monetize their sites with ads will understand.

We wanted to name it "Publisher Ads" broadly (instead of Google), because we want to encourage other ad tech vendors to contribute audits and best practices of their own.

"Ad publishing" doesn't really work, but publishers don't publish ads, they publish content.

"AdSpeed" was a bit more exciting and memorable, but "Publisher Ads Audits" is more descriptive and doesn't have any branding conflicts.

**Comment by warrengm** [comment]
Bikeshedding is totally warranted here. We don't want yet another project or folder renaming and it's important to set the right precedent for future plugins

Some notes about naming

- "Audits" came when we needed a more descriptive name. "Publisher Ads Lighthouse Plugin" isn't super clear for users who are unfamiliar with Lighthouse but "Publisher Ads Audits for Lighthouse" immediately indicates that it audits your site. That said, I complete agree that "audits" is superfluous in this context
- In addition to the reasons Rob mentioned, we dropped "speed" because some audits are not speed related, e.g. audits about ad placement.
- We're trying to avoid being Google-focused long term. In a world with stack packs, we can genericize most audits and offer google-specific guidance in the stack pack.
- Google Ads is a specific product (FKA AdWords), but the audits are focused on sellside products, Google Ad Manager and AdSense.
- "Publisher" is meant to clarify that the audits are focused on sites and not creatives. We've discussed building audits for creatives, which would be "Advertiser/Marketer Ads Audits".

**Comment by wardpeet** [comment]
With the name publisher ads we're probably targeting people who are in charge of advertising inside publisher companies or know about the ecosystem. Maybe we should look into that direction. I'm not super good with names but what if we look more in the area of `lighthouse-plugin-adserver-integration` or `lighthouse-plugin-ssp-integration`

**Comment by robhazan** [comment]
We're providing recommendations that address ad server tagging code, as
well as SSP, exchange, and DSP tags. I think using the generic "ads" makes
the most sense.

**Comment by paulirish** [comment]
Thanks everyone for the context. Super useful.

I realized I'm thinking of a few places this "name" is used, so let's enumerate them:

1. Name of this project, shown in the readme
1. The repository name
1. The name of the npm package
1. The string shown to users in DevTools, etc where they can include this plugin
1. What people search for to find this (probably a mix of the above)

----------

For the DevTools checkbox, it seems like "Publisher Ads" is right.
Given that, I'd think the npm package name would be `lighthouse-plugin-publisher-ads`.
And as far as project name, "Publisher Ads (Audits) for Lighthouse" seems groovy. 😎 

So wdyt about 1) `lighthouse-plugin-publisher-ads` for folder/package.json name and 2) doing a s/pub/publisher/ on the repo name?

**Comment by jburger424** [comment]
@paulirish All that SGTM :slightly_smiling_face: will wait for agreement from @robhazan and @thebengeu before making the changes

**Comment by robhazan** [comment]
The names "Publisher Ads Audits for Lighthouse" and "Publisher Ads Lighthouse Plugin" are both fine with me.

**Comment by thebengeu** [comment]
One way of thinking about this is that we're referring to 2 things:

1. The implementation: Lighthouse plugin
2. What the implementation (plugin) provides: Audits.

So everything that @paulirish proposed SGTM, with the addition that I think the project repo name, since it's the implementation, could be "Publisher Ads Lighthouse Plugin", for consistency.

For docs/links outside of this repo, I think it would be more descriptive to use "audits", e.g. "enable the Publisher Ads audits under Lighthouse's Community Plugins section", "using the Publisher Ads Audits for Lighthouse", etc.

**Comment by warrengm** [comment]
SGTM

**Pull request merged**
