### PR TITLE
Upgrade to Lighthouse 6.0.0-beta.0

### PR DESCRIPTION
**Pull request by jburger424**
- Include 10th percentile scores to support Lighthouse v6.0 `computeLogNormalScore` changes (thanks @brendankenny!).
- Update runWarnings usage (thanks @paulirish!).
- Include numericUnits.
- Other minor fixes.

### CODE REVIEW

**Comment by jburger424** [comment]
@googlebot I consent.

**Comment by jburger424** [comment]
@brendankenny can you consent to googlebot?

**Comment by brendankenny** [comment]
@googlebot I consent.

**Comment by paulirish** [comment]
@googlebot I consent

**Comment by jburger424** [comment]
Force merging this to release beta package for LH, will resolve travis issues tomorrow.

**Pull request merged**
