### PR TITLE
Update to Lighthouse v8.4.0

### PR DESCRIPTION
**Pull request by jonkeller**

### CODE REVIEW

**Review by jburger424 — COMMENTED** [review]
At this point, I think it would be better to split of the version bump into a separate PR after this, given that there are quite a few changes associated with the Lighthouse update.

**Comment by jonkeller** [comment]
Happy to split, assuming that the changes from #298 will function at 8.0.0. Will give it a shot...

**Comment by jonkeller** [comment]
Oh wait, I may have misunderstood you. Are you saying this:
PR A: Brendan's changes + my smoke test changes; PR B: bump to LH 8.4.0 and bump our version to 1.5.1
or this:
PR A: Bump to LH 8.4.0, Brendan's changes, my smoke test changes; PR B: bump our version to 1.5.1
In my previous comment I thought you were saying the first thing but now I suspect you're saying the second thing...

**Review by jburger424 — APPROVED** [review]

**Comment by jburger424** [comment]
Sorry! I meant what you did, so just having the version change in a follow up.

**Pull request merged**
